### ISSUE TITLE
bosh upload release: "Expect:100-Continue" header in uploads to Ceph RGW S3-compatible api in Mirantis OpenStack 9.1 are broke

### ISSUE THREAD

**Issue by markstokan** [cloudfoundry/bosh-s3cli#16]
(SEE THE SECOND COMMENT FOR A BETTER DESCRIPTION)

At a user level when you try to do a 'bosh upload release' with a Mirantis 9.1 OpenStack cluster (ceph 0.94.6) as your external blob store, it fails with the error:

```
ERROR -- DirectorJobRunner: Failed to create S3 object, code 1, output: '', error: '2017/02/07 22:11:09 Upload retry limit exceeded: MultipartUpload: upload multipart failed
	upload id: 2~EkVqqp9F03ogG0ICbCIYfYagfmHhI_A
caused by: InvalidArgument:
	status code: 400, request id: tx00000000000000000071f-00589a45fd-68a1d-default
2017/02/07 22:11:09 performing operation put: upload retry limit exceeded: MultipartUpload: upload multipart failed
	upload id: 2~EkVqqp9F03ogG0ICbCIYfYagfmHhI_A
caused by: InvalidArgument:
	status code: 400, request id: tx00000000000000000071f-00589a45fd-68a1d-default
'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/blobstore_client-260.5.0/lib/blobstore_client/s3cli_blobstore_client.rb:115:in `store_in_s3'
```

This was previously working (and continues to) for the Ops Manager team on their Mirantis 6 OpenStack cluster (ceph 0.80.9).

The `store_in_s3` function uses the s3cli command to upload files.  We were able to reproduce this problem directly using that command and found that the problem was specific to multi-part uploads.  Small uploads work fine.

```
/:/var/vcap/data/tmp/director# /var/vcap/data/packages/s3cli/8cbc6ee1b5acaac18c63fafc5989bd6911c9be83-f1febb77993dcec28a75c887593e0ad31867096d/bin/s3cli -c s3_blobstore_config-5aeac0fd-0340-48a4-aa18-82186f4a0371 put s3_blobstore_config-5aeac0fd-0340-48a4-aa18-82186f4a0371 foo
2017/02/07 00:01:37 Successfully uploaded file to http:/boshtest/foo
```

```
/:/var/vcap/data/tmp/director# /var/vcap/data/packages/s3cli/8cbc6ee1b5acaac18c63fafc5989bd6911c9be83-f1febb77993dcec28a75c887593e0ad31867096d/bin/s3cli -c s3_blobstore_config-5aeac0fd-0340-48a4-aa18-82186f4a0371 put ubuntu-16.04.1-desktop-amd64.iso ubuntu-16.04.1-desktop-amd64.iso
2017/02/07 00:02:14 Upload retry limit exceeded: MultipartUpload: upload multipart failed
    upload id: 2~xCkzsLekMnvMAa_e2VH5cvgqPvsNp3k
caused by: InvalidArgument:
    status code: 400, request id: tx00000000000000002f892-0058990e85-57636-default
2017/02/07 00:02:14 performing operation put: upload retry limit exceeded: MultipartUpload: upload multipart failed
    upload id: 2~xCkzsLekMnvMAa_e2VH5cvgqPvsNp3k
caused by: InvalidArgument:
    status code: 400, request id: tx00000000000000002f892-0058990e85-57636-default
```

On the OpenStack side we have two sets of logs reporting errors...

The Ceph Rados Gateway logs return a status `400` and the fcgi-pm binary logs a `503`.

Toolsmiths team investigated on behalf of the Ops Manager team.  Notes in Tracker story: 

https://www.pivotaltracker.com/story/show/138956065

**Comment by cppforlife** [comment]
cc @voelzmo

**Comment by markstokan** [comment]
Changed the issue title to more accurately reflect the real problem.

We witnessed an upload that was small enough to not trigger multi-part uploads was also broken.

Eventually tracked this down to uploads greater than 2MB, which use the "Expect:100-Continue" header.

Example of failure:

```
$ s3cli -c ~/.s3cli-os1-mos9 put ~/Downloads/TonysPizzaNapoletana_Menu-12162015.pdf TonysPizzaNapoletana_Menu-12162015.pdf
2017/02/07 15:10:27 Successfully uploaded file to http:/boshtest/TonysPizzaNapoletana_Menu-12162015.pdf
$  ls -l ~/Downloads/TonysPizzaNapoletana_Menu-12162015.pdf
-rw-r--r--@ 1 pivotal  staff  3791950 Nov  1 17:33 /Users/pivotal/Downloads/TonysPizzaNapoletana_Menu-12162015.pdf
```

Client reports success, but no object appears in container.  RGW returns a `400`.  fcgi-pm returns `503`.

We were able to "fix" this by disabling the use of this header in s3cli...

```diff
--- a/client/sdk.go
+++ b/client/sdk.go
@@ -23,6 +24,7 @@ func NewSDK(c config.S3Cli) (*s3.S3, error) {
        s3Config := aws.NewConfig().
                WithLogLevel(aws.LogOff).
                WithS3ForcePathStyle(true).
+               WithS3Disable100Continue(true).
```

Confirmed the object uploaded successfully.

**Comment by cunnie** [comment]
Opened this story, awaiting prioritization:  https://www.pivotaltracker.com/story/show/139336523

**Comment by voelzmo** [comment]
I think we have two problems here, I would prefer to not solve them by excluding the expects-100-continue header.

1. This seems to be either a bug in Ceph or in the configuration of your OpenStack installation. Officially, [Ceph supports Http 100 continue ](http://docs.ceph.com/docs/giant/install/install-ceph-gateway/), just [like S3 does](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html).

2. The S3 client should not fail, if the server doesn't reply with 100-continue, [according to the spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html)
> Therefore, when a client sends this header field to an origin server (possibly via a proxy) from which it has never seen a 100 (Continue) status, the client SHOULD NOT wait for an indefinite period before sending the request body.

Some background why the expects-100-continue header makes sense: Especially when uploading blobs, you don't want to receive some HTTP 401/403 after uploading 2GB of blobs. Therefore, a client can send just the headers before sending the actual payload, so the server can check authorization against the credentials provided in the header. I think we shouldn't simply disable this as proposed in the story.

Wdyt?

**Comment by markstokan** [comment]
I suspect the issue is not with Ceph RADOSGW support for "100-Continue" but with the apache2/mod_proxy_fcgi infrastructure Mirantis has moved to in later releases of their OpenStack distribution.  

I have a workaround for this on the OpenStack controller where I tell Apache to drop all "Expect" headers before processing the incoming requests.  Change the virtual host configuration that handles S3 requests (/etc/apache2/sites-enabled/rgw.conf) to include snippet:

```
  <IfModule mod_headers.c>
  RequestHeader unset Expect early
  </IfModule>
```

We're implementing this on our cluster to unblock the Ops Manager team.

**Comment by voelzmo** [comment]
@markstokan so you're saying Mirantis uses a different apache configuration than the one described in http://docs.ceph.com/docs/giant/install/install-ceph-gateway/#apache-fastcgi-w-100-continue ?

**Comment by markstokan** [comment]
@voelzmo Correct.  Mirantis appears to have embraced the new configuration with uses mod_proxy_fcgi as documented at: http://docs.ceph.com/docs/jewel/man/8/radosgw/#configuration
