### ISSUE TITLE
Upload object with public-read ACL

### ISSUE THREAD

**Issue by arvatoth-vcc** [cloudfoundry/bosh-s3cli#17]
Hello,

Can you help me, how can I upload any object with public-read ACL? I found this ACL in the go source code, but I do not known how/where can I specify.

Thank you!

**Comment by cppforlife** [comment]
@arvatoth-vcc could you describe your use case a bit better?

**Comment by arvatoth-vcc** [comment]
I would like to upload objects with public-read ACL. For example with gsutil:

```gsutil cp -a public-read sound.mp4 gs://owngarden```
