### ISSUE TITLE
Introduce Alicloud integration tests

### ISSUE THREAD

**Issue by jrussett** [cloudfoundry/bosh-s3cli#19]
Looking through the codebase, there is support for using a Alicloud-centric config when using the s3cli. However, when we look at the pipeline and in the test resources, we see that there are no Alicloud specific integration tests.

@xiaozhu36 could you or your team please write some integration tests that cover general interaction with Alicloud and test any Alicloud specific functionality before we can close this PR?

**Comment by xiaozhu36** [comment]
HI @jrussett Thanks for your sugestion. I have add alibaba cloud integration test #20 . Please check it.
