### ISSUE TITLE
Upload specifying metadata

### ISSUE THREAD

**Issue by sscarduzio** [cloudfoundry/bosh-s3cli#28]
Hi I'm using this tool to upload to S3 html files, but I need them to be set with metadata Content-Type: text/html. So browsers can display the HTML. 

How to do this?

**Comment by rkoster** [comment]
The bosh-s3cli is an internal component embedded in the [bosh stemcell](http://bosh.io/stemcells), it is not meant to be used as a stand-alone cli. Please use something like https://github.com/koblas/s3-cli if you need a cli written in go to interact with s3.
