### ISSUE TITLE
invalid use of ,string struct tag, trying to unmarshal "" into int

### ISSUE THREAD

**Issue by Jerryhax** [cloudfoundry/bosh-s3cli#34]
I got a error "2023/10/25 16:11:37 json: invalid use of ,string struct tag, trying to unmarshal "" into int" when I put a object to my s3 <remote-blob>. 
this is my config.json

> {
    "bucket_name":"qwe",
    "credentials_source":"static",
    "access_key_id":"access_key_id",
    "secret_access_key":"secret_access_key",
    "region":"",
    "host":"IP",
    "port":80,
    "ssl_verify_peer":false,
    "use_ssl":false,
    **"signature_version":"",**
    "server_side_encryption":"",
    "sse_kms_key_id":"",
    "multipart_upload":false
}

why not change  ' "signature_version":      "\<string\> (optional)" ' in README.md to  '"signature_version":      "\<string\> required [ 2 | 4 ]"'  or    '"signature_version":  \<int\> [ 2 | 4 ]' ?

**Comment by rkoster** [comment]
We would love to review a PR that makes those changes to the README.md.

**Comment by Malsourie** [comment]
Hi @Jerryhax , optional means that it is not necessary to provide that config parameter, it does not mean that if you do not want to specify it, you set the value as an empty string. Simply remove the key "signature_version" and then it should work.

**Comment by Jerryhax** [comment]
> Hi @Jerryhax , `optional` means that it is not necessary to provide that config parameter, it does not mean that if you do not want to specify it, you set the value as an empty string. Simply remove the key "signature_version" and then it should work.

thx，I got it . 
It works when I remove the key "signature_version" in my config.json 
setting the value to null has the same effect.

**Comment by beyhan** [comment]
Ok, we are closing this. Please reopen if still needed.
